In [21]:
import tensorflow as tf
import numpy as np

xy = np.loadtxt('data-01-test-score.csv', delimiter = ',', dtype = np.float32)
x_data = xy[: , 0:-1]
y_data = xy[: , [-1]]

print(x_data.shape, "\n", x_data, "\n", len(x_data))
print(y_data.shape, "\n", y_data, "\n", len(y_data))

(25, 3) 
 [[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]
 [ 69.  74.  77.]
 [ 47.  56.  60.]
 [ 87.  79.  90.]
 [ 79.  70.  88.]
 [ 69.  70.  73.]
 [ 70.  65.  74.]
 [ 93.  95.  91.]
 [ 79.  80.  73.]
 [ 70.  73.  78.]
 [ 93.  89.  96.]
 [ 78.  75.  68.]
 [ 81.  90.  93.]
 [ 88.  92.  86.]
 [ 78.  83.  77.]
 [ 82.  86.  90.]
 [ 86.  82.  89.]
 [ 78.  83.  85.]
 [ 76.  83.  71.]
 [ 96.  93.  95.]] 
 25
(25, 1) 
 [[152.]
 [185.]
 [180.]
 [196.]
 [142.]
 [101.]
 [149.]
 [115.]
 [175.]
 [164.]
 [141.]
 [141.]
 [184.]
 [152.]
 [148.]
 [192.]
 [147.]
 [183.]
 [177.]
 [159.]
 [177.]
 [175.]
 [175.]
 [149.]
 [192.]] 
 25


In [22]:
x = tf.placeholder(tf.float32, shape = [None, 3])
y = tf.placeholder(tf.float32, shape = [None, 1])

w = tf.Variable(tf.random_normal([3, 1]), name = 'weight')
b = tf.Variable(tf.random_normal([1]), name = 'bias')

hypothesis = tf.matmul(x,w) + b

cost = tf.reduce_mean(tf.square(hypothesis - y))
optimizer = tf.train.GradientDescentOptimizer(learning_rate = 1e-5)
train = optimizer.minimize(cost)

sess = tf.Session()
sess.run(tf.global_variables_initializer())

for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train], feed_dict = {x:x_data, y:y_data})
    if step%10 == 0:
        print(step, "cost: ", cost_val, "\nprediction\n", hy_val)

0 cost:  6439.9883 
prediction
 [[ 82.29584 ]
 [ 91.01819 ]
 [ 93.56323 ]
 [101.86408 ]
 [ 67.900085]
 [ 49.916065]
 [ 79.056244]
 [ 62.572247]
 [ 83.62436 ]
 [ 77.24297 ]
 [ 73.85698 ]
 [ 69.59734 ]
 [ 96.31523 ]
 [ 79.680954]
 [ 78.30623 ]
 [ 93.16281 ]
 [ 73.47689 ]
 [ 96.31314 ]
 [ 93.046036]
 [ 84.29782 ]
 [ 91.24127 ]
 [ 86.129196]
 [ 87.67707 ]
 [ 82.3534  ]
 [ 95.365005]]
10 cost:  20.258621 
prediction
 [[157.09421 ]
 [180.95001 ]
 [182.15802 ]
 [198.35638 ]
 [136.49063 ]
 [100.497734]
 [151.2841  ]
 [116.116646]
 [167.68642 ]
 [155.1206  ]
 [143.44804 ]
 [138.23155 ]
 [187.84045 ]
 [155.75894 ]
 [150.87138 ]
 [184.42517 ]
 [145.93372 ]
 [182.99011 ]
 [180.29654 ]
 [162.36392 ]
 [175.94229 ]
 [170.50104 ]
 [168.4285  ]
 [157.75519 ]
 [188.56131 ]]
20 cost:  19.842087 
prediction
 [[157.59344 ]
 [181.58089 ]
 [182.76326 ]
 [199.02144 ]
 [136.97456 ]
 [100.867226]
 [151.78206 ]
 [116.48508 ]
 [168.29037 ]
 [155.69583 ]
 [143.93091 ]
 [138.72354 ]
 [188.46025 ]
 [156.2678  ]
 [15

280 cost:  17.283392 
prediction
 [[157.16211]
 [181.8224 ]
 [182.59785]
 [198.98549]
 [137.22856]
 [101.36547]
 [151.75604]
 [116.44464]
 [168.86841]
 [156.61769]
 [143.98436]
 [139.16676]
 [188.1555 ]
 [155.85976]
 [151.4802 ]
 [185.3803 ]
 [146.09303]
 [183.46803]
 [180.45125]
 [162.44391]
 [176.55595]
 [171.41513]
 [168.9038 ]
 [157.4948 ]
 [189.27089]]
290 cost:  17.195768 
prediction
 [[157.14629]
 [181.8311 ]
 [182.59172]
 [198.98401]
 [137.23778]
 [101.3835 ]
 [151.75487]
 [116.44287]
 [168.88928]
 [156.65096]
 [143.98615]
 [139.18272]
 [188.14435]
 [155.84492]
 [151.48373]
 [185.39151]
 [146.0812 ]
 [183.4635 ]
 [180.43552]
 [162.42778]
 [176.5567 ]
 [171.42656]
 [168.9007 ]
 [157.46748]
 [189.2731 ]]
300 cost:  17.108868 
prediction
 [[157.13054 ]
 [181.83974 ]
 [182.58559 ]
 [198.9825  ]
 [137.24696 ]
 [101.40145 ]
 [151.75368 ]
 [116.441086]
 [168.91006 ]
 [156.6841  ]
 [143.98792 ]
 [139.19862 ]
 [188.13322 ]
 [155.83017 ]
 [151.48723 ]
 [185.40266 ]
 [146.06944 ]
 [183.45

550 cost:  15.158678 
prediction
 [[156.7569  ]
 [182.0459  ]
 [182.44116 ]
 [198.94661 ]
 [137.46675 ]
 [101.82707 ]
 [151.72324 ]
 [116.394196]
 [169.4029  ]
 [157.46729 ]
 [144.02927 ]
 [139.57497 ]
 [187.8716  ]
 [155.48346 ]
 [151.5679  ]
 [185.66689 ]
 [145.79532 ]
 [183.34726 ]
 [180.05023 ]
 [162.03201 ]
 [176.57271 ]
 [171.7077  ]
 [168.82202 ]
 [156.79817 ]
 [189.32915 ]]
560 cost:  15.088909 
prediction
 [[156.74274]
 [182.05376]
 [182.43571]
 [198.94524]
 [137.47516]
 [101.84321]
 [151.72198]
 [116.39223]
 [169.42157]
 [157.49687]
 [144.0308 ]
 [139.58922]
 [187.86176]
 [155.47046]
 [151.57088]
 [185.67691]
 [145.78513]
 [183.34286]
 [180.0363 ]
 [162.01768]
 [176.5732 ]
 [171.71791]
 [168.81908]
 [156.77394]
 [189.33125]]
570 cost:  15.019688 
prediction
 [[156.72864]
 [182.06158]
 [182.4303 ]
 [198.94386]
 [137.48355]
 [101.85927]
 [151.72073]
 [116.39025]
 [169.44019]
 [157.52634]
 [144.03232]
 [139.6034 ]
 [187.85196]
 [155.4575 ]
 [151.57382]
 [185.68687]
 [145.775  ]


790 cost:  13.635014 
prediction
 [[156.43234 ]
 [182.22685 ]
 [182.31677 ]
 [198.91461 ]
 [137.66116 ]
 [102.19653 ]
 [151.69269 ]
 [116.345505]
 [169.83075 ]
 [158.14316 ]
 [144.06381 ]
 [139.90059 ]
 [187.6475  ]
 [155.1879  ]
 [151.63394 ]
 [185.89627 ]
 [145.5655  ]
 [183.24362 ]
 [179.73221 ]
 [161.70435 ]
 [176.58214 ]
 [171.94171 ]
 [168.75314 ]
 [156.24518 ]
 [189.37851 ]]
800 cost:  13.57792 
prediction
 [[156.41951 ]
 [182.23405 ]
 [182.31186 ]
 [198.91331 ]
 [137.66895 ]
 [102.211136]
 [151.69138 ]
 [116.3434  ]
 [169.84767 ]
 [158.16982 ]
 [144.06514 ]
 [139.91344 ]
 [187.63869 ]
 [155.1763  ]
 [151.63646 ]
 [185.90535 ]
 [145.55658 ]
 [183.2394  ]
 [179.71968 ]
 [161.69142 ]
 [176.58244 ]
 [171.95097 ]
 [168.75035 ]
 [156.2234  ]
 [189.38051 ]]
810 cost:  13.521335 
prediction
 [[156.40672]
 [182.24123]
 [182.30699]
 [198.91205]
 [137.6767 ]
 [102.22571]
 [151.69008]
 [116.34131]
 [169.86453]
 [158.19635]
 [144.06647]
 [139.92625]
 [187.62993]
 [155.16478]
 [151.63898]
 [

1050 cost:  12.295253 
prediction
 [[156.11473]
 [182.40587]
 [182.19609]
 [198.88243]
 [137.85507]
 [102.55783]
 [151.65855]
 [116.28966]
 [170.24922]
 [158.80006]
 [144.0962 ]
 [140.21794]
 [187.43141]
 [154.90434]
 [151.69438]
 [186.12059]
 [145.3491 ]
 [183.13545]
 [179.42409]
 [161.38588]
 [176.58745]
 [172.17046]
 [168.6824 ]
 [155.70892]
 [189.42949]]
1060 cost:  12.24931 
prediction
 [[156.10318 ]
 [182.41243 ]
 [182.19174 ]
 [198.88126 ]
 [137.86221 ]
 [102.570984]
 [151.65724 ]
 [116.28747 ]
 [170.26445 ]
 [158.82388 ]
 [144.09737 ]
 [140.22946 ]
 [187.42361 ]
 [154.89415 ]
 [151.6965  ]
 [186.12875 ]
 [145.3414  ]
 [183.13138 ]
 [179.41293 ]
 [161.37434 ]
 [176.58757 ]
 [172.17877 ]
 [168.67976 ]
 [155.68951 ]
 [189.43141 ]]
1070 cost:  12.203727 
prediction
 [[156.09166]
 [182.41896]
 [182.1874 ]
 [198.88008]
 [137.86931]
 [102.58407]
 [151.65591]
 [116.28526]
 [170.27962]
 [158.8476 ]
 [144.09851]
 [140.24095]
 [187.41586]
 [154.88399]
 [151.69862]
 [186.13689]
 [145.33376

1300 cost:  11.253234 
prediction
 [[155.83932]
 [182.56287]
 [182.09245]
 [198.85378]
 [138.02649]
 [102.87088]
 [151.62515]
 [116.2338 ]
 [170.61191]
 [159.36555]
 [144.12303]
 [140.49193]
 [187.24701]
 [154.6637 ]
 [151.74301]
 [186.31497]
 [145.16922]
 [183.03549]
 [179.15973]
 [161.11174]
 [176.58847]
 [172.3685 ]
 [168.61803]
 [155.24838]
 [189.47614]]
1310 cost:  11.215862 
prediction
 [[155.82889]
 [182.56888]
 [182.08855]
 [198.85269]
 [138.03307]
 [102.88276]
 [151.6238 ]
 [116.23153]
 [170.62566]
 [159.38693]
 [144.12402]
 [140.5023 ]
 [187.24008]
 [154.65468]
 [151.7448 ]
 [186.32237]
 [145.16257]
 [183.03157]
 [179.14977]
 [161.1014 ]
 [176.58846]
 [172.37602]
 [168.61552]
 [155.231  ]
 [189.47797]]
1320 cost:  11.178807 
prediction
 [[155.81847 ]
 [182.57483 ]
 [182.08464 ]
 [198.85156 ]
 [138.0396  ]
 [102.894585]
 [151.62245 ]
 [116.22926 ]
 [170.63934 ]
 [159.40819 ]
 [144.125   ]
 [140.51262 ]
 [187.23317 ]
 [154.64568 ]
 [151.74654 ]
 [186.3297  ]
 [145.15591 ]
 [183

1580 cost:  10.315105 
prediction
 [[155.5621 ]
 [182.7228 ]
 [181.9892 ]
 [198.8241 ]
 [138.20259]
 [103.18572]
 [151.58737]
 [116.16954]
 [170.9767 ]
 [159.93028]
 [144.14865]
 [140.76642]
 [187.06456]
 [154.42708]
 [151.78786]
 [186.5105 ]
 [144.9965 ]
 [182.9282 ]
 [178.89671]
 [160.83795]
 [176.58565]
 [172.56758]
 [168.54996]
 [154.78963]
 [189.5257 ]]
1590 cost:  10.285431 
prediction
 [[155.55276]
 [182.72823]
 [181.98573]
 [198.82307]
 [138.20857]
 [103.19631]
 [151.58603]
 [116.16721]
 [170.98898]
 [159.94922]
 [144.14949]
 [140.77563]
 [187.05847]
 [154.41922]
 [151.78928]
 [186.51706]
 [144.99086]
 [182.92447]
 [178.88791]
 [160.82878]
 [176.58548]
 [172.57428]
 [168.5476 ]
 [154.77428]
 [189.5274 ]]
1600 cost:  10.256003 
prediction
 [[155.54347]
 [182.73363]
 [181.98228]
 [198.82207]
 [138.21454]
 [103.20687]
 [151.58466]
 [116.16491]
 [171.00122]
 [159.96806]
 [144.15031]
 [140.7848 ]
 [187.05243]
 [154.4114 ]
 [151.79071]
 [186.52362]
 [144.98523]
 [182.92073]
 [178.879

1830 cost:  9.641452 
prediction
 [[155.33961]
 [182.85274]
 [181.9072 ]
 [198.79959]
 [138.34686]
 [103.43819]
 [151.55363]
 [116.11131]
 [171.26932]
 [160.37982]
 [144.16808]
 [140.98564]
 [186.92078]
 [154.24185]
 [151.82045]
 [186.66728]
 [144.86484]
 [182.83661]
 [178.68814]
 [160.62003]
 [176.5802 ]
 [172.72711]
 [168.49261]
 [154.42545]
 [189.56764]]
1840 cost:  9.61726 
prediction
 [[155.33115]
 [182.85768]
 [181.90408]
 [198.79863]
 [138.35236]
 [103.44776]
 [151.55228]
 [116.10898]
 [171.2804 ]
 [160.3968 ]
 [144.16876]
 [140.99393]
 [186.91536]
 [154.2349 ]
 [151.82161]
 [186.67322]
 [144.85995]
 [182.83301]
 [178.68027]
 [160.61176]
 [176.57991]
 [172.73315]
 [168.49037]
 [154.41168]
 [189.56926]]
1850 cost:  9.593262 
prediction
 [[155.32275 ]
 [182.86264 ]
 [181.90102 ]
 [198.7977  ]
 [138.3579  ]
 [103.457306]
 [151.55093 ]
 [116.10664 ]
 [171.29146 ]
 [160.41374 ]
 [144.16951 ]
 [141.00221 ]
 [186.90999 ]
 [154.22798 ]
 [151.82278 ]
 [186.67915 ]
 [144.85512 ]
 [182.829

In [25]:
print("Your score will be ", sess.run(hypothesis, feed_dict = {x:[[100,70,101]]}))

Your score will be  [[176.83673]]
