In [1]:
import tensorflow as tf

x1_data = [73., 93., 89., 96., 73.]
x2_data = [80., 88., 91., 98., 66.]
x3_data = [75., 93., 90., 100., 70.]
y_data = [152., 185., 180., 196., 142.]

x1 = tf.placeholder(tf.float32)
x2 = tf.placeholder(tf.float32)
x3 = tf.placeholder(tf.float32)
y = tf.placeholder(tf.float32)

w1 = tf.Variable(tf.random_normal([1]), name = 'weight1')
w2 = tf.Variable(tf.random_normal([1]), name = 'weight2')
w3 = tf.Variable(tf.random_normal([1]), name = 'weight3')
b = tf.Variable(tf.random_normal([1]), name = 'bias')

hypothesis = x1*w1 + x2*w2 + x3*w3 + b

cost = tf.reduce_mean(tf.square(hypothesis-y))
optimizer = tf.train.GradientDescentOptimizer(learning_rate = 1e-5)
train = optimizer.minimize(cost)

sess = tf.Session()
sess.run(tf.global_variables_initializer())

for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train], feed_dict={x1:x1_data, x2:x2_data, x3:x3_data, y:y_data})
    
    if step % 10 == 0:
        print(step, "cost: ", cost_val, "\nprediction: \n", hy_val)

0 cost:  10570.962 
prediction: 
 [64.47788  71.962265 73.460846 82.03439  52.12005 ]
10 cost:  16.026653 
prediction: 
 [155.34688 181.20674 181.08743 199.23793 135.45201]
20 cost:  15.854901 
prediction: 
 [155.6078  181.54698 181.40889 199.58884 135.71747]
30 cost:  15.780133 
prediction: 
 [155.59457 181.55768 181.40567 199.58617 135.73154]
40 cost:  15.705719 
prediction: 
 [155.58058 181.56737 181.40146 199.58243 135.74483]
50 cost:  15.631821 
prediction: 
 [155.56662 181.57701 181.39728 199.57872 135.75806]
60 cost:  15.558238 
prediction: 
 [155.55266 181.58661 181.39307 199.57498 135.77124]
70 cost:  15.485098 
prediction: 
 [155.53877 181.5962  181.38892 199.57129 135.78441]
80 cost:  15.412252 
prediction: 
 [155.52492 181.60577 181.38474 199.56757 135.79755]
90 cost:  15.339874 
prediction: 
 [155.51111 181.61531 181.3806  199.56389 135.81065]
100 cost:  15.267856 
prediction: 
 [155.49731 181.62482 181.37648 199.56023 135.82373]
110 cost:  15.196268 
prediction: 
 [155.48

940 cost:  10.407113 
prediction: 
 [154.46635 182.33739 181.06795 199.27977 136.80714]
950 cost:  10.361331 
prediction: 
 [154.45546 182.34491 181.0647  199.27673 136.8176 ]
960 cost:  10.31584 
prediction: 
 [154.44463 182.35243 181.06146 199.27373 136.82802]
970 cost:  10.270534 
prediction: 
 [154.4338  182.35994 181.05826 199.27074 136.83844]
980 cost:  10.225541 
prediction: 
 [154.423   182.36737 181.05501 199.26772 136.84879]
990 cost:  10.180717 
prediction: 
 [154.41223 182.37483 181.05179 199.26472 136.85913]
1000 cost:  10.13619 
prediction: 
 [154.40152 182.38228 181.04861 199.26175 136.86945]
1010 cost:  10.091808 
prediction: 
 [154.3908  182.38966 181.04541 199.25874 136.87975]
1020 cost:  10.04774 
prediction: 
 [154.38011 182.39705 181.04222 199.25575 136.88998]
1030 cost:  10.003897 
prediction: 
 [154.36949 182.40442 181.03905 199.2528  136.90024]
1040 cost:  9.960311 
prediction: 
 [154.35887 182.41176 181.03589 199.24985 136.91043]
1050 cost:  9.916895 
predictio

1960 cost:  6.791894 
prediction: 
 [153.49869 183.00763 180.7802  199.0037  137.74406]
1970 cost:  6.765199 
prediction: 
 [153.49051 183.01332 180.77777 199.00128 137.75208]
1980 cost:  6.7386627 
prediction: 
 [153.48233 183.01897 180.77534 198.99887 137.76006]
1990 cost:  6.712251 
prediction: 
 [153.4742  183.02464 180.77295 198.99648 137.76802]
2000 cost:  6.685988 
prediction: 
 [153.46608 183.03026 180.77054 198.99408 137.77597]
