In [2]:
import tensorflow as tf
filename_queue = tf.train.string_input_producer(['data-01-test-score.csv'], shuffle = False, name = 'filename_queue')

reader = tf.TextLineReader()
key, value = reader.read(filename_queue)

record_defaults = [[0.], [0.], [0.], [0.]]
xy = tf.decode_csv(value, record_defaults = record_defaults)

train_x_batch, train_y_batch = \
tf.train.batch([xy[0:-1], xy[-1:]], batch_size = 10)

x = tf.placeholder(tf.float32, shape = [None, 3])
y = tf.placeholder(tf.float32, shape = [None, 1])
w = tf.Variable(tf.random_normal([3,1]), name = 'weight')
b = tf.Variable(tf.random_normal([1]), name = 'bias')
hypothesis = tf.matmul(x,w)+b
cost = tf.reduce_mean(tf.square(hypothesis - y))
optimizer = tf.train.GradientDescentOptimizer(learning_rate = 1e-5)
train = optimizer.minimize(cost)
sess = tf.Session()
sess.run(tf.global_variables_initializer())

coord = tf.train.Coordinator()
threads = tf.train.start_queue_runners(sess = sess, coord = coord)

for step in range(2001):
    x_batch, y_batch = sess.run([train_x_batch, train_y_batch])
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train], feed_dict = {x:x_batch, y:y_batch})
    if step % 10 == 0:
        print(step, "cost :", cost_val, "\nprediction\n", hy_val)

coord.request_stop()
coord.join(threads)
    

0 cost : 1708.1248 
prediction
 [[125.102615]
 [140.21036 ]
 [143.784   ]
 [152.4792  ]
 [107.66255 ]
 [ 71.563965]
 [110.65248 ]
 [ 77.52634 ]
 [123.51108 ]
 [104.21245 ]]
10 cost : 98.62473 
prediction
 [[160.23871]
 [182.50752]
 [185.4236 ]
 [197.85265]
 [139.91722]
 [ 95.39003]
 [144.63416]
 [102.74155]
 [163.08653]
 [140.92967]]
20 cost : 95.80324 
prediction
 [[160.43959]
 [182.80876]
 [185.68768]
 [198.16353]
 [140.14262]
 [ 95.59911]
 [144.8847 ]
 [102.95043]
 [163.41039]
 [141.2864 ]]
30 cost : 94.91344 
prediction
 [[160.40488]
 [182.8265 ]
 [185.67262]
 [198.17029]
 [140.15182]
 [ 95.64858]
 [144.90752]
 [102.99044]
 [163.46904]
 [141.39723]]
40 cost : 94.044365 
prediction
 [[160.36876]
 [182.84225]
 [185.65578]
 [198.175  ]
 [140.15952]
 [ 95.69675]
 [144.92871]
 [103.02912]
 [163.52567]
 [141.50592]]
50 cost : 93.183266 
prediction
 [[160.33284 ]
 [182.85793 ]
 [185.63899 ]
 [198.17966 ]
 [140.16718 ]
 [ 95.744675]
 [144.94984 ]
 [103.0677  ]
 [163.582   ]
 [141.61414 ]]


490 cost : 62.363495 
prediction
 [[158.91241 ]
 [183.46825 ]
 [184.97084 ]
 [198.36815 ]
 [140.4528  ]
 [ 97.640045]
 [145.80344 ]
 [104.62796 ]
 [165.80959 ]
 [145.91006 ]]
500 cost : 61.80204 
prediction
 [[158.88353]
 [183.48045]
 [184.95714]
 [198.37207]
 [140.45825]
 [ 97.67861]
 [145.8212 ]
 [104.66051]
 [165.85489]
 [145.99786]]
510 cost : 61.24579 
prediction
 [[158.8548  ]
 [183.49265 ]
 [184.94353 ]
 [198.37599 ]
 [140.46365 ]
 [ 97.716995]
 [145.83893 ]
 [104.69295 ]
 [165.90001 ]
 [146.08527 ]]
520 cost : 60.6948 
prediction
 [[158.8262 ]
 [183.50473]
 [184.92996]
 [198.3799 ]
 [140.46904]
 [ 97.75519]
 [145.85658]
 [104.72525]
 [165.94489]
 [146.17229]]
530 cost : 60.149086 
prediction
 [[158.79774]
 [183.51675]
 [184.91646]
 [198.38377]
 [140.47435]
 [ 97.79319]
 [145.87418]
 [104.75743]
 [165.98956]
 [146.25888]]
540 cost : 59.608498 
prediction
 [[158.76945 ]
 [183.5287  ]
 [184.90303 ]
 [198.38763 ]
 [140.47963 ]
 [ 97.831024]
 [145.8917  ]
 [104.78951 ]
 [166.03404 ]

1010 cost : 39.23087 
prediction
 [[157.58383 ]
 [184.0213  ]
 [184.33582 ]
 [198.55424 ]
 [140.68483 ]
 [ 99.41683 ]
 [146.64497 ]
 [106.169975]
 [167.89769 ]
 [149.97667 ]]
1020 cost : 38.888958 
prediction
 [[157.56148]
 [184.03044]
 [184.32503]
 [198.5575 ]
 [140.68837]
 [ 99.4468 ]
 [146.6596 ]
 [106.19682]
 [167.9329 ]
 [150.04568]]
1030 cost : 38.550495 
prediction
 [[157.53922]
 [184.03949]
 [184.31429]
 [198.56071]
 [140.69186]
 [ 99.47661]
 [146.67418]
 [106.22356]
 [167.96793]
 [150.11433]]
1040 cost : 38.215126 
prediction
 [[157.51706]
 [184.04851]
 [184.30357]
 [198.56395]
 [140.69534]
 [ 99.50626]
 [146.6887 ]
 [106.2502 ]
 [168.00279]
 [150.1827 ]]
1050 cost : 37.882942 
prediction
 [[157.49503]
 [184.05748]
 [184.29292]
 [198.56715]
 [140.69878]
 [ 99.5358 ]
 [146.70319]
 [106.27676]
 [168.03749]
 [150.25073]]
1060 cost : 37.55404 
prediction
 [[157.4731 ]
 [184.06639]
 [184.28232]
 [198.57033]
 [140.70218]
 [ 99.56517]
 [146.71758]
 [106.3032 ]
 [168.072  ]
 [150.3184

1520 cost : 25.380627 
prediction
 [[156.57304]
 [184.42537]
 [183.84326]
 [198.7051 ]
 [140.82831]
 [100.77244]
 [147.3259 ]
 [107.42094]
 [169.49072]
 [153.11636]]
1530 cost : 25.171295 
prediction
 [[156.55568]
 [184.43216]
 [183.83469]
 [198.70778]
 [140.83044]
 [100.79578]
 [147.33801]
 [107.44321]
 [169.51814]
 [153.17079]]
1540 cost : 24.96398 
prediction
 [[156.53838]
 [184.43889]
 [183.82617]
 [198.71046]
 [140.83257]
 [100.81899]
 [147.35007]
 [107.46541]
 [169.54543]
 [153.22496]]
1550 cost : 24.758602 
prediction
 [[156.52118]
 [184.44559]
 [183.81767]
 [198.71312]
 [140.83467]
 [100.84212]
 [147.36209]
 [107.48753]
 [169.57259]
 [153.27888]]
1560 cost : 24.555218 
prediction
 [[156.50406 ]
 [184.45226 ]
 [183.80923 ]
 [198.71577 ]
 [140.83673 ]
 [100.86511 ]
 [147.37407 ]
 [107.509575]
 [169.59961 ]
 [153.33257 ]]
1570 cost : 24.35387 
prediction
 [[156.48703]
 [184.45886]
 [183.80083]
 [198.71843]
 [140.83876]
 [100.88799]
 [147.38599]
 [107.53152]
 [169.62651]
 [153.3859

In [3]:
print("Your score will be ", sess.run(hypothesis, feed_dict = {x:[[100,70,101]]}))

Your score will be  [[176.19263]]
