In [3]:
import tensorflow as tf

x_data = [[73., 80., 75.], [93., 88., 93.], [89., 91., 90.], [96., 98., 100.], [73., 66., 70.]]
y_data = [[152.], [185.], [180.], [196.], [142.]]

x = tf.placeholder(tf.float32, shape = [None, 3])
y = tf.placeholder(tf.float32, shape = [None, 1])
w = tf.Variable(tf.random_normal([3,1]), name = 'weight')
b = tf.Variable(tf.random_normal([1]), name = 'bias')

hypothesis = tf.matmul(x,w) + b

cost = tf.reduce_mean(tf.square(hypothesis-y))
optimizer = tf.train.GradientDescentOptimizer(learning_rate = 1e-5)
train = optimizer.minimize(cost)

sess = tf.Session()
sess.run(tf.global_variables_initializer())

for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train], feed_dict={x: x_data, y:y_data})
    
    if step % 10 == 0:
        print(step, "cost: ", cost_val, "\nprediction: \n", hy_val)

0 cost:  55039.53 
prediction: 
 [[-46.861412]
 [-72.30158 ]
 [-63.13312 ]
 [-67.982735]
 [-59.61124 ]]
10 cost:  57.10961 
prediction: 
 [[160.5381 ]
 [177.03131]
 [182.51071]
 [199.51987]
 [130.57828]]
20 cost:  56.30791 
prediction: 
 [[161.13712]
 [177.8053 ]
 [183.24529]
 [200.3224 ]
 [131.17993]]
30 cost:  56.01112 
prediction: 
 [[161.1105 ]
 [177.82721]
 [183.23889]
 [200.31805]
 [131.2079 ]]
40 cost:  55.716026 
prediction: 
 [[161.08206]
 [177.84676]
 [183.23024]
 [200.31123]
 [131.23402]]
50 cost:  55.422497 
prediction: 
 [[161.0537 ]
 [177.86626]
 [183.22163]
 [200.30443]
 [131.26009]]
60 cost:  55.130474 
prediction: 
 [[161.02542]
 [177.88571]
 [183.21304]
 [200.29765]
 [131.2861 ]]
70 cost:  54.84004 
prediction: 
 [[160.99721]
 [177.9051 ]
 [183.20445]
 [200.29088]
 [131.31203]]
80 cost:  54.551308 
prediction: 
 [[160.9691 ]
 [177.92445]
 [183.19594]
 [200.28413]
 [131.33789]]
90 cost:  54.264038 
prediction: 
 [[160.94104]
 [177.94373]
 [183.18741]
 [200.27739]
 [131

870 cost:  36.032066 
prediction: 
 [[158.97324]
 [179.29715]
 [182.59006]
 [199.8016 ]
 [133.17667]]
880 cost:  35.84465 
prediction: 
 [[158.95064]
 [179.3127 ]
 [182.5832 ]
 [199.79608]
 [133.19754]]
890 cost:  35.658302 
prediction: 
 [[158.9281 ]
 [179.3282 ]
 [182.57639]
 [199.79059]
 [133.21835]]
900 cost:  35.472878 
prediction: 
 [[158.90562]
 [179.34367]
 [182.56958]
 [199.7851 ]
 [133.23912]]
910 cost:  35.288475 
prediction: 
 [[158.88321]
 [179.3591 ]
 [182.56277]
 [199.77963]
 [133.25983]]
920 cost:  35.105114 
prediction: 
 [[158.86086]
 [179.37448]
 [182.556  ]
 [199.77419]
 [133.28047]]
930 cost:  34.92267 
prediction: 
 [[158.83855]
 [179.3898 ]
 [182.54922]
 [199.76874]
 [133.30107]]
940 cost:  34.741283 
prediction: 
 [[158.81633]
 [179.4051 ]
 [182.5425 ]
 [199.7633 ]
 [133.32161]]
950 cost:  34.560814 
prediction: 
 [[158.79414]
 [179.42035]
 [182.53577]
 [199.75787]
 [133.34209]]
960 cost:  34.381287 
prediction: 
 [[158.77205]
 [179.43558]
 [182.52905]
 [199.752

1820 cost:  22.066547 
prediction: 
 [[157.08022]
 [180.60014]
 [182.01671]
 [199.3348 ]
 [134.93053]]
1830 cost:  21.95431 
prediction: 
 [[157.0628 ]
 [180.61217]
 [182.01147]
 [199.33047]
 [134.94675]]
1840 cost:  21.842678 
prediction: 
 [[157.04544]
 [180.62413]
 [182.00621]
 [199.32613]
 [134.9629 ]]
1850 cost:  21.731623 
prediction: 
 [[157.02809]
 [180.63605]
 [182.00096]
 [199.3218 ]
 [134.97902]]
1860 cost:  21.621265 
prediction: 
 [[157.0108 ]
 [180.64793]
 [181.99573]
 [199.31746]
 [134.99506]]
1870 cost:  21.51148 
prediction: 
 [[156.9936 ]
 [180.6598 ]
 [181.99052]
 [199.31316]
 [135.0111 ]]
1880 cost:  21.402168 
prediction: 
 [[156.9764 ]
 [180.67163]
 [181.98532]
 [199.30885]
 [135.02708]]
1890 cost:  21.293499 
prediction: 
 [[156.95926]
 [180.68344]
 [181.98015]
 [199.30457]
 [135.04303]]
1900 cost:  21.185436 
prediction: 
 [[156.94218]
 [180.69522]
 [181.97499]
 [199.30031]
 [135.05894]]
1910 cost:  21.077993 
prediction: 
 [[156.92516]
 [180.70695]
 [181.96985]