In [7]:
import tensorflow as tf

x_data = [[1,2,1,1],[2,1,3,2],[3,1,3,4],[4,1,5,5],[1,7,5,5],[1,2,5,6],[1,6,6,6],[1,7,7,7]]
y_data = [[0,0,1],[0,0,1],[0,0,1],[0,1,0],[0,1,0],[0,1,0],[1,0,0],[1,0,0]]

X = tf.placeholder("float",[None,4])
Y = tf.placeholder("float",[None,3])
nb_classes = 3

W = tf.Variable(tf.random_normal([4,nb_classes]), name = 'weight')
b = tf.Variable(tf.random_normal([nb_classes]), name = 'bias')

hypothesis = tf.nn.softmax(tf.matmul(X,W) + b)
cost = tf.reduce_mean(-tf.reduce_sum(Y * tf.log(hypothesis), axis = 1))
train = tf.train.GradientDescentOptimizer(learning_rate = 0.1).minimize(cost)

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    
    for step in range(2001):
        sess.run(train, feed_dict = {X:x_data, Y:y_data})
        if step % 200 == 0:
            print(step, sess.run(cost, feed_dict = {X:x_data, Y:y_data}))
    
    #testing
    print('\n--------testing--------')
    all = sess.run(hypothesis, feed_dict={X: [[1, 11, 7, 9], [1, 3, 4, 3], [1, 1, 0, 1]]})
    print(all, sess.run(tf.argmax(all, 1)))

0 7.5528054
200 0.52954197
400 0.42534995
600 0.35273623
800 0.28382778
1000 0.22115833
1200 0.20061632
1400 0.18378809
1600 0.16950971
1800 0.1572462
2000 0.14660251

--------testing--------
[[1.49336609e-03 9.98497009e-01 9.67378128e-06]
 [9.20064509e-01 6.39980286e-02 1.59375463e-02]
 [1.09857625e-08 2.61091482e-04 9.99738872e-01]] [1 0 2]
